
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: weather-api-dev
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: weather
        role: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: gcr.io/cloud-solutions-images/weather-api:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 81
        ports:
        - name: backend
          containerPort: 9005
