apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weather-ui-dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather
        tier: backend
        track: stable
    spec:
      containers:
        - name: weather-ui
          image: "gcr.io/google-samples/weather-ui:latest"
          ports:
            - name: http
              containerPort: 80
