apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weather-api-dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather
        tier: backend
    spec:
      containers:
        - name: weather-api
          image: "gcr.io/cloud-solutions-images/weather-api:1.0.0"
          ports:
            - name: http
              containerPort: 9393
