apiVersion: apps/v2
kind: Deployment
metadata:
  name: weather-ui-dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather
        tier: backend
    spec:
      containers:
        - name: weather-ui
          image: "gcr.io/google-samples/weather-ui:1.0"
          ports:
            - name: http
              containerPort: 80
