apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weather-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weather
        tier: frontend
    spec:
      containers:
      - name: weather-proxy
        image: "gcr.io/cloud-solutions-images/weather-proxy:1.0.0"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
