package main

type WUHistory struct {
	History struct {
		Dailysummary []struct {
			Coolingdegreedays       string `json:"coolingdegreedays"`
			Coolingdegreedaysnormal string `json:"coolingdegreedaysnormal"`
			Date                    struct {
				Hour   string `json:"hour"`
				Mday   string `json:"mday"`
				Min    string `json:"min"`
				Mon    string `json:"mon"`
				Pretty string `json:"pretty"`
				Tzname string `json:"tzname"`
				Year   string `json:"year"`
			} `json:"date"`
			Fog                                string `json:"fog"`
			Gdegreedays                        string `json:"gdegreedays"`
			Hail                               string `json:"hail"`
			Heatingdegreedays                  string `json:"heatingdegreedays"`
			Heatingdegreedaysnormal            string `json:"heatingdegreedaysnormal"`
			Humidity                           string `json:"humidity"`
			Maxdewpti                          string `json:"maxdewpti"`
			Maxdewptm                          string `json:"maxdewptm"`
			Maxhumidity                        string `json:"maxhumidity"`
			Maxpressurei                       string `json:"maxpressurei"`
			Maxpressurem                       string `json:"maxpressurem"`
			Maxtempi                           string `json:"maxtempi"`
			Maxtempm                           string `json:"maxtempm"`
			Maxvisi                            string `json:"maxvisi"`
			Maxvism                            string `json:"maxvism"`
			Maxwspdi                           string `json:"maxwspdi"`
			Maxwspdm                           string `json:"maxwspdm"`
			Meandewpti                         string `json:"meandewpti"`
			Meandewptm                         string `json:"meandewptm"`
			Meanpressurei                      string `json:"meanpressurei"`
			Meanpressurem                      string `json:"meanpressurem"`
			Meantempi                          string `json:"meantempi"`
			Meantempm                          string `json:"meantempm"`
			Meanvisi                           string `json:"meanvisi"`
			Meanvism                           string `json:"meanvism"`
			Meanwdird                          string `json:"meanwdird"`
			Meanwdire                          string `json:"meanwdire"`
			Meanwindspdi                       string `json:"meanwindspdi"`
			Meanwindspdm                       string `json:"meanwindspdm"`
			Mindewpti                          string `json:"mindewpti"`
			Mindewptm                          string `json:"mindewptm"`
			Minhumidity                        string `json:"minhumidity"`
			Minpressurei                       string `json:"minpressurei"`
			Minpressurem                       string `json:"minpressurem"`
			Mintempi                           string `json:"mintempi"`
			Mintempm                           string `json:"mintempm"`
			Minvisi                            string `json:"minvisi"`
			Minvism                            string `json:"minvism"`
			Minwspdi                           string `json:"minwspdi"`
			Minwspdm                           string `json:"minwspdm"`
			Monthtodatecoolingdegreedays       string `json:"monthtodatecoolingdegreedays"`
			Monthtodatecoolingdegreedaysnormal string `json:"monthtodatecoolingdegreedaysnormal"`
			Monthtodateheatingdegreedays       string `json:"monthtodateheatingdegreedays"`
			Monthtodateheatingdegreedaysnormal string `json:"monthtodateheatingdegreedaysnormal"`
			Monthtodatesnowfalli               string `json:"monthtodatesnowfalli"`
			Monthtodatesnowfallm               string `json:"monthtodatesnowfallm"`
			Precipi                            string `json:"precipi"`
			Precipm                            string `json:"precipm"`
			Precipsource                       string `json:"precipsource"`
			Rain                               string `json:"rain"`
			Since1jancoolingdegreedays         string `json:"since1jancoolingdegreedays"`
			Since1jancoolingdegreedaysnormal   string `json:"since1jancoolingdegreedaysnormal"`
			Since1julheatingdegreedays         string `json:"since1julheatingdegreedays"`
			Since1julheatingdegreedaysnormal   string `json:"since1julheatingdegreedaysnormal"`
			Since1julsnowfalli                 string `json:"since1julsnowfalli"`
			Since1julsnowfallm                 string `json:"since1julsnowfallm"`
			Since1sepcoolingdegreedays         string `json:"since1sepcoolingdegreedays"`
			Since1sepcoolingdegreedaysnormal   string `json:"since1sepcoolingdegreedaysnormal"`
			Since1sepheatingdegreedays         string `json:"since1sepheatingdegreedays"`
			Since1sepheatingdegreedaysnormal   string `json:"since1sepheatingdegreedaysnormal"`
			Snow                               string `json:"snow"`
			Snowdepthi                         string `json:"snowdepthi"`
			Snowdepthm                         string `json:"snowdepthm"`
			Snowfalli                          string `json:"snowfalli"`
			Snowfallm                          string `json:"snowfallm"`
			Thunder                            string `json:"thunder"`
			Tornado                            string `json:"tornado"`
		} `json:"dailysummary"`
		Date struct {
			Hour   string `json:"hour"`
			Mday   string `json:"mday"`
			Min    string `json:"min"`
			Mon    string `json:"mon"`
			Pretty string `json:"pretty"`
			Tzname string `json:"tzname"`
			Year   string `json:"year"`
		} `json:"date"`
		Observations []struct {
			Conds string `json:"conds"`
			Date  struct {
				Hour   string `json:"hour"`
				Mday   string `json:"mday"`
				Min    string `json:"min"`
				Mon    string `json:"mon"`
				Pretty string `json:"pretty"`
				Tzname string `json:"tzname"`
				Year   string `json:"year"`
			} `json:"date"`
			Dewpti     string `json:"dewpti"`
			Dewptm     string `json:"dewptm"`
			Fog        string `json:"fog"`
			Hail       string `json:"hail"`
			Heatindexi string `json:"heatindexi"`
			Heatindexm string `json:"heatindexm"`
			Hum        string `json:"hum"`
			Icon       string `json:"icon"`
			Metar      string `json:"metar"`
			Precipi    string `json:"precipi"`
			Precipm    string `json:"precipm"`
			Pressurei  string `json:"pressurei"`
			Pressurem  string `json:"pressurem"`
			Rain       string `json:"rain"`
			Snow       string `json:"snow"`
			Tempi      string `json:"tempi"`
			Tempm      string `json:"tempm"`
			Thunder    string `json:"thunder"`
			Tornado    string `json:"tornado"`
			Utcdate    struct {
				Hour   string `json:"hour"`
				Mday   string `json:"mday"`
				Min    string `json:"min"`
				Mon    string `json:"mon"`
				Pretty string `json:"pretty"`
				Tzname string `json:"tzname"`
				Year   string `json:"year"`
			} `json:"utcdate"`
			Visi       string `json:"visi"`
			Vism       string `json:"vism"`
			Wdird      string `json:"wdird"`
			Wdire      string `json:"wdire"`
			Wgusti     string `json:"wgusti"`
			Wgustm     string `json:"wgustm"`
			Windchilli string `json:"windchilli"`
			Windchillm string `json:"windchillm"`
			Wspdi      string `json:"wspdi"`
			Wspdm      string `json:"wspdm"`
		} `json:"observations"`
		Utcdate struct {
			Hour   string `json:"hour"`
			Mday   string `json:"mday"`
			Min    string `json:"min"`
			Mon    string `json:"mon"`
			Pretty string `json:"pretty"`
			Tzname string `json:"tzname"`
			Year   string `json:"year"`
		} `json:"utcdate"`
	} `json:"history"`
	Response struct {
		Features struct {
			History int `json:"history"`
		} `json:"features"`
		TermsofService string `json:"termsofService"`
		Version        string `json:"version"`
	} `json:"response"`
}
