apiVersion: v1
kind: Service
metadata:
  name: weather-proxy-srv
spec:
  selector:
    app: weather
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
